os: Visual Studio 2017
cache:
  - node_modules
environment:
  GH_TOKEN:
    secure: q0seCidIf7NXsK7KPL9ts9xlWCFkRmicxcTci3u0Cj9uFgc4GFxHOIkIGtbFy3Eq # your encrypted token from GitHub
  matrix:
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - cmd: rd /s /q www\remote\arduino\darwin
  - npx electron-builder
  - Invoke-WebRequest "https://static-hk-robobloq.oss-cn-hongkong.aliyuncs.com/certificate/q-release.exe" -OutFile ".\q-release.exe"
  - q-release.exe upload "releases\*.exe"
artifacts:
  - path: 'releases\*.*'
deploy:
  provider: GitHub
  auth_token:
    secure: q0seCidIf7NXsK7KPL9ts9xlWCFkRmicxcTci3u0Cj9uFgc4GFxHOIkIGtbFy3Eq # your encrypted token from GitHub
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only